### ISSUE TITLE
Does ModArgparser do right with list

### ISSUE THREAD

**Issue by Misca1234** [pointhi/kicad-footprint-generator#142]
It seems that you can not add a list with attribute required false, that is

parser.add_parameter("size", type=list, required=False)

If size is not present in yml file you get the following error message

```
parser.run()
  File "C:\Users\stefan\KiCad\NyVersion\kicad-footprint-generator\scripts\Battery\..\..\KicadModTree\ModArgparser.py", line 134, in run
    self._parse_and_execute_yml(filepath)
  File "C:\Users\stefan\KiCad\NyVersion\kicad-footprint-generator\scripts\Battery\..\..\KicadModTree\ModArgparser.py", line 162, in _parse_and_execute_yml
    self._execute_script(**kwargs)  # now we can execute the script
  File "C:\Users\stefan\KiCad\NyVersion\kicad-footprint-generator\scripts\Battery\..\..\KicadModTree\ModArgparser.py", line 253, in _execute_script
    parsed_args[k] = type(v.get('default'))
TypeError: 'NoneType' object is not iterable

```

**Comment by pointhi** [comment]
it is somehow to expect. We try to get the parameter, and if it does not exist ```None``` is returned. Then we do a cast to the expected type, which works for int/float, but not for lists.

This can be solved by setting a default value of the correct type:

```python
parser.add_parameter("size", type=list, required=False, default=[])
```

If you want to get 2D dimensions, I would recommend you to use the internal type in the parser (which adds some more error checking as well)
```python
parser.add_parameter("size", type=Vector2D, required=False, default=[0, 0])
```

Probably we should make it mandatory to have a default value set, or return None if no value is provided (which would be probably the cleanest solution).
