### ISSUE TITLE
Directory not visible

### ISSUE THREAD

**Issue by Misca1234** [pointhi/kicad-footprint-generator#145]
Acording to push 
https://github.com/pointhi/kicad-footprint-generator/commit/6722aacba47ebac8b524622b9ada096a5537174d

scripts/Packages/Package_DFN_QFN/ipc_dfn_qfn_generator.py
Was updated

But if you look at 
https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages

scripts/Packages/Package_DFN_QFN

Is not visible?

**Comment by pointhi** [comment]
This file is not merged yet: https://github.com/pointhi/kicad-footprint-generator/pull/125
