### ISSUE TITLE
How to exclude pins for Package_Gullwing__QFP_SOIC_SO

### ISSUE THREAD

**Issue by Misca1234** [pointhi/kicad-footprint-generator#195]
I want to do the Diode_SOT-553 from 
https://www.diodes.com/assets/Datasheets/AH1806.pdf

with help of 
Package_Gullwing__QFP_SOIC_SO\ipc_gullwing_generator.py

But I can not find any way to excluding pins, is it possible at all with this script  ?

**Comment by pointhi** [comment]
#197 should have fixed it
