### ISSUE TITLE
Workflow how to create a new generator module release it and copy the the new footprints to the kicad repo

### ISSUE THREAD

**Issue by waschhauser** [pointhi/kicad-footprint-generator#417]
Hi Thomas,

is there a workflow or a best practice how the develop a new generator module release it (pull request). And how to transfer the new footprints to the github repo?

I'd like to implement a generator for the molex sl connectors.
When my work on my fork is finished what to do?

I think I have to create a pull request for the new generator module.
If the pull request will be accepted then I can create a pull request for the kicad footprint repo (for this request a link to the generator module if required).
But what if my kicad pull request will receive some review comments. Then I have to make the modifications for the generator. Create pull request and so on.

Or do you make the review for the created footprints during the review of the generator module?

Is there a best practice / workflow how the make this changes in an easy way without creating a lot of work for a lot of people?

Thanks,
Richard

**Comment by chschlue** [comment]
I'm not @pointhi but I think it's the other way round.
Generator PRs get merged after the generated FPs are merged.

**Comment by waschhauser** [comment]
Thx
