### ISSUE TITLE
Molex KK 396 is missing

### ISSUE THREAD

**Issue by jabdoa2** [pointhi/kicad-footprint-generator#423]
Those connectors went missing: https://github.com/KiCad/Connectors_Molex.pretty/blob/master/Molex_KK-41791-02_02x3.96mm_Straight.kicad_mod. Is this intentional? I added them back then. Should I submit them again or should I host them somewhere else? Those connectors are typically used in pinball.

**Comment by poeschlr** [comment]
You can add whatever footprint generator you desire to this repo.
Footprints can be added to the official library as long as they fulfil the current version of the library convention. (so taking some old footprint could mean it must be adapted.)
