### ISSUE TITLE
[Question] Add Phoenix PT 2,5 to script

### ISSUE THREAD

**Issue by GMagician** [pointhi/kicad-footprint-generator#427]
Is there any possibility to add to scritp (and to Kicad libaries) the Terminal block in the title?

The only differences I saw with 1,5 version are:
Back area is 4,5mm and not 4
Total H is 13,5 and not 11,4
pin protrusion is 4,1 and not 3,5

here is pdf reference:
https://datasheet.octopart.com/1935776-Phoenix-Contact-datasheet-9718601.pdf

I'm not used to phyton and can't do myself, sorry

Thanks

**Comment by poeschlr** [comment]
While we appreciate your interest, we are sadly not able to take requests. Neither here nor on the official library.
