### ISSUE TITLE
PadArray exclude pad only works with pure numerical initial pin.

### ISSUE THREAD

**Issue by poeschlr** [pointhi/kicad-footprint-generator#436]
Failing line of code: https://github.com/pointhi/kicad-footprint-generator/blob/25fd7492c5247cb0572e674a2939daf58b03f5d8/KicadModTree/nodes/specialized/PadArray.py#L234

It might be a good idea to add quite a few testcases for ensuring this can not be broken again in the future.

**Comment by poeschlr** [comment]
Well i kind of missed that https://github.com/pointhi/kicad-footprint-generator/pull/392 already attempts to fix this.

**Comment by antoniovazquezblanco** [comment]
#392 will wait for this fix to be merged. Thanks!

**Comment by antoniovazquezblanco** [comment]
This has been fixed by #392 

Please close
