### ISSUE TITLE
yaml file for mounting holes?

### ISSUE THREAD

**Issue by cnieves1** [pointhi/kicad-footprint-generator#472]
Hi,
I wanted to add some more mounting holes, for M1.4 and M1.6mm.
I found there is a script to generate them, at scripts/Mounting_Hardware/mounting_hole.py
but I see it requires a .yaml file.

I undertand I would need to modify that .yaml file to add these mounting holes, but where is it?

Thanks,

**Comment by pointhi** [comment]
Thanks for noticing. I uploaded my example file: 1c1399b590dcb6c6290c6edae12b6439ce100776
