### ISSUE TITLE
Silk placed on THT pads by kicad_mod.createNumberedPadsTHT?

### ISSUE THREAD

**Issue by evanshultz** [pointhi/kicad-footprint-generator#48]
I'm just starting to check out the scripting tools, so forgive me if this is a stupid question.

After seeing my first footprint in KiCad, I noticed the silk layer was turned on. Looking at [kicad_mod.py](https://github.com/pointhi/kicad-footprint-generator/blob/master/kicad_mod/kicad_mod.py), I see that silk is indeed a layer generated for THT pads:
![image](https://user-images.githubusercontent.com/1936989/28728055-01187dd6-737c-11e7-8d35-2a603792ab86.png)

Is this correct? I would not expect silk to be a desired layer for THT pads.

If this needs to be corrected, I'm happy to submit a PR.

**Comment by pointhi** [comment]
kicad_mod.py is deprecated, and is no longer developed
