### ISSUE TITLE
Similar script directory names

### ISSUE THREAD

**Issue by yankee14** [pointhi/kicad-footprint-generator#568]
What is the difference between `/scripts/Packages/Package_DFN_QFN` and `/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON`? Is the former destined to be obsoleted?

**Comment by evanshultz** [comment]
Yes, and in fact it already has. There is only a single YAML file with package size information in the former folder; the footprint generator script itself and all other files are already gone.

**Comment by yankee14** [comment]
@evanshultz , thanks for the information!
