### ISSUE TITLE
Footprint generator for AC/DC, DC/DC converters

### ISSUE THREAD

**Issue by Werni2A** [pointhi/kicad-footprint-generator#598]
Hi, I was wondering if there exists any footprint generator for packages like the following. These packages are widely used in AC/DC and DC/DC converters therefore a single generator would be useful.

Hence I haven't found any script I will give it a try to write my own generator. 
- Do you know if there is something special I need to keep in mind?
- What is the preferred type of generator? It looks like the YAML based variants are state-of-the-art?

![image](https://user-images.githubusercontent.com/58232418/91655575-e593c880-eab1-11ea-81e1-c93010ca1d57.png)

**Comment by Franck78** [comment]
It looks like this script
https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/general/StandardBox.py

provides a function to call from your script that will do most of the job.

and.......

DC/DC AC/DC converter script already exists !!!!!!!!!

**Comment by Werni2A** [comment]
@Franck78 Good that I asked. I will take a look at the script in a few days :+1: 

> DC/DC AC/DC converter script already exists !!!!!!!!!

Do you mean there is another script that does the conversion or the one you linked above? If there is another one, could you point me into the right direction?

**Comment by Franck78** [comment]
When I look at the KiCad lib AC/DC DC/DC I see a lot of footprint like you RECOM.
So, I think it's just a single line (for each footprint you want) to add in the generator.py (or similar name) found in the AC/DC DC/DC subdir.

**Comment by Werni2A** [comment]
I directly skipped the files in [Converter_DCDC](https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Converter_DCDC) as I read the function name "QFN" but they really seem to generate those kind of packages. Thanks.
